#!/bin/bash

PI_HOST=192.168.1.200
PI_USER=pi

EXECUTABLE=$1
PATH_TO_MAIN=$2
PI_DEST_FOLDER=$3

cd $PATH_TO_MAIN
env GOOS=linux GOARCH=arm GOARM=7 go build -o $EXECUTABLE .
scp $EXECUTABLE $PI_USER@$PI_HOST:$PI_DEST_FOLDER
